# словник з розшифровками статусів погоди
weather_code_ua = {
    0: 'sunny',
    1: 'Переважно безхмарно',
    2: 'Хмарно з проясненнями',
    3: 'Похмуро', 45: 'Туман',
    48: 'Іней',
    51: 'Слабка мряка',
    53: 'Помірна мряка',
    55: 'Густа мряка',
    56: 'Легкий крижаний дощ',
    57: 'Щільний крижаний дощ',
    61: 'Слабкий дощ',
    63: 'Помірний дощ',
    65: 'Сильний дощ',
    66: 'Слабкий крижаний дощ',
    67: 'Сильний крижаний дощ',
    71: 'Слабкий снігопад',
    73: 'Помірний снігопад',
    75: 'Сильний снігопад',
    77: 'Снігові крупинки',
    80: 'Слабка злива',
    81: 'Помірна злива',
    82: 'Сильна злива',
    85: 'Невеликий снігопад',
    86: 'Сильний снігопад',
}

weather_code = {
    0: 'Clear sky',
    1: 'Mainly clear',
    2: 'Partly cloudy',
    3: 'Overcast',
    45: 'Fog',
    48: 'Depositing rime fog',
    51: 'Light drizzle',
    53: 'Moderate drizzle',
    55: 'Dense intensity drizzle',
    56: 'Light freezing drizzle',
    57: 'Dense intensity freezing drizzle',
    61: 'Slight rain',
    63: 'Moderate rain',
    65: 'Heavy intensity rain',
    66: 'Light freezing rain',
    67: 'Heavy intensity freezing rain',
    71: 'Slight snow fall',
    73: 'Moderate snow fall',
    75: 'Heavy intensity snow fall',
    77: 'Snow grains',
    80: 'Slight rain showers',
    81: 'Moderate rain showers',
    82: 'Violent rain showers',
    85: 'Slight snow showers',
    86: 'Heavy snow showers',
    95: 'Thunderstorm',
    96: 'Thunderstorm with slight hail',
    99: 'Thunderstorm with moderate hail'
}
